name: messagedirect
description: MessageDirect

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  intl_phone_number_input: ^0.7.0
  libphonenumber: ^2.0.0
  cupertino_icons: ^1.0.2
  country_picker: ^2.0.11
  flutter_awesome_buttons: ^1.1.0
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.7
  url_launcher: ^6.0.18
  quick_actions: ^0.6.0
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 900